apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: postgresql
  name: gitops-sealedsecret-admin
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-sealedsecret-admin
  namespace: postgresql
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: Role
  name: gitops-sealedsecret-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'postgresql-sample'
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'git@github.com:linux-foundation-summit-sealed-secrets/lms-postgres-sample.git'
    path: ./k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true