apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: seal-secret
spec:
  params:
   - name: SEALED_SECRETS_CONTROLLER_NS
     description: Namespace the sealed-secrets controller is deployed in
     default: kube-system
   - name: INPUT_SECRET
     description: Name and path to secret for kubeseal to encrypt
   - name: OUTPUT_SEALED_SECRET
     description: Name of output sealed secret

  steps:
    - image: 'quay.io/samuele_chinellato_ibm/ubi8-kubeseal:0.0.1'
      name: kubeseal-reencrypt-secret
      script: >
        #!/bin/sh

        echo "Encrypting secret $(params.INPUT_SECRET)"
        
        kubeseal --controller-namespace $(params.SEALED_SECRETS_CONTROLLER_NS) <$(params.INPUT_SECRET) > $(params.OUTPUT_SEALED_SECRET)

        echo "Created secret $(params.OUTPUT_SEALED_SECRET):"

        cat $(params.OUTPUT_SEALED_SECRET)


