apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: seal-secret-pipeline-run-
spec:
  params:
    - name: source-repo
      value: git@github.com:linux-foundation-summit-sealed-secrets/lms-postgres-sample.git
    - name: sealed_secrets_controller_ns
      value: sealed-secrets
    - name: namespace
      value: 'postgresql'
    - name: target-namespace
      value: 'postgresql'
    - name: secret_filename
      value: 'secret.yaml'
    - name: sealed_secret_filename
      value: 'sealed-secret.yaml'
  pipelineRef:
    name: seal-secret-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
