apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: trigger
spec:
  serviceAccountName: pipeline
  triggers:
    - name: twilio-trigger
      bindings:
        - ref: bind-twilio-trigger
      template:
        ref: twilio-trigger
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: twilio-trigger
  name: el-trigger
spec:
  port:
    targetPort: http-listener
  to:
    kind: ""
    name: el-trigger
    weight: null
