apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: commit-manifest
spec:
  params:
    - name: app-name
      description: name of the app
    - name: sha
      description: sha of the current commit
    - name: gitops-repo
  workspaces:
    - name: source
      description: contains the cloned git repo
  steps:
    - name: gitops
      image: docker.io/csantanapr/helm-kubectl-curl-git-jq-yq
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -e
        git config --global user.email "gitops@cloudnativetoolkit.dev"
        git config --global user.name "Tekton Pipeline"
        git clone $(params.gitops-repo) gitops
        cd gitops
        rm $(params.app-name)/manifests.yaml
        cp ../source/k8s/manifests.yaml $(params.app-name)
        if [[ $(git status -s | wc -l) -eq 0 ]]; then
          echo "No changes"
          exit 0
        fi
        git add "$(params.app-name)/manifests.yaml"
        git commit -m "update $(params.app-name) to commit $(params.sha)"
        git push