apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: commit-sha
      description: SHA from Commit
  workspaces:
    - name: source
      description: contains the cloned git repo
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      name: apply-sealed-secret
      workingDir: $(workspaces.source.path)
      script: >
        #!/bin/sh

        oc apply -f $(params.SECRET_FILENAME)
    - name: deploy
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh

        oc apply -f deployment.yaml
    - name: update-label
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh

        oc patch DeploymentConfig postgresql \
          --type='json' -p='[{"op": "replace", "path": "/metadata/labels/sha", "value":"$(params.commit-sha)"}]'
        
        
        oc patch secret $(params.new-secret-name) \
          --type='json' -p='[{"op": "replace", "path": "/metadata/labels/sha", "value":"$(params.commit-sha)"}]'