apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: force-key-change
spec:
  workspaces:
    - name: source
      description: contains the cloned git repo
  params:
    - name: NAMESPACE
      description: namespace of the controller
      default: sealed-secrets
  steps:
    - name: force-compromised
      workingDir: $(workspaces.source.path)
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      script: |
        #!/bin/sh

        LBL="sealedsecrets.bitnami.com/sealed-secrets-key=active"

        SECRET_NAME=$(oc get secrets -l $LBL -n $(params.NAMESPACE) -o jsonpath='{..name}') 
        
        echo $SECRET_NAME
        
        oc -n $(params.NAMESPACE) label secrets $SECRET_NAME \
         sealedsecrets.bitnami.com/sealed-secrets-key=compromised \
         --overwrite=true
    - name: restart-pod
      workingDir: $(workspaces.source.path)
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools 
      script: |
        #!/bin/sh

        echo "restarting sealed secrets controller pod..."

        PODNAME=$(oc get pod -n $(params.NAMESPACE) \
         -l  name=sealed-secrets-controller | grep sealed-secrets-controller- | awk '{print $1}')

        echo "deleting pod $PODNAME ..."
        oc delete pod -n $(params.NAMESPACE) \
         $PODNAME

        echo "waiting for sealed secrets controller to be in a ready state..."

        oc wait -n $(params.NAMESPACE) --for condition=available deployment/sealed-secrets-controller --timeout=300s
