apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: force-key-change
spec:
  steps:
    - name: force-compromised
      image: docker.io/alpine/k8s:1.20.7
      script: |
        #!/bin/sh

        SECRET_NAME=$(kubectl get secrets -l sealedsecrets.bitnami.com/sealed-secrets-key=active -n kube-system) 
        
        echo $SECRET_NAME
        
        kubectl -n kube-system label secrets $(SECRET_NAME) sealedsecrets.bitnami.com/sealed-secrets-key=compromised --overwrite=true
    - name: restart-pod
      image: docker.io/alpine/k8s:1.20.7
      script: |
        #!/bin/sh

        #TODO: Add Pod Reset 