apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: force-key-change
spec:
  steps:
    - name: force-compromised
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      script: |
        #!/bin/sh

        SECRET_NAME=$(oc get secrets -l sealedsecrets.bitnami.com/sealed-secrets-key=active -n kube-system) 
        
        echo $SECRET_NAME
        
        oc -n kube-system label secrets $(SECRET_NAME) sealedsecrets.bitnami.com/sealed-secrets-key=compromised --overwrite=true
    - name: restart-pod
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      script: |
        #!/bin/sh

        #TODO: Add Pod Reset 