apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-secret
spec:
  workspaces:
    - name: source
      description: contains the cloned git repo
  params:
    - name: SECRET_NAME 
    - name: NAMESPACE
  steps:
    - name: replace-secret
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      workingDir: $(workspaces.source.path)
      script: >
        #!/bin/sh

        echo "Getting Secret..."  

        oc get secret $(params.SECRET_NAME) -n $(params.NAMESPACE) -o yaml > secret.yaml

        cat secret.yaml