apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: new-secret
spec:
  params:
    - name: SECRET_LENGTH
      default: '20'
    - name: PROJECT_NAME
      default: 'database-demo'
    - name: SECRET_NAME      
      default: postgresql
    - name: DB_NAME
      default: db
    - name: USERNAME
      default: 'database_user'
  results:
    - name: name
      description: New Secret Name
  steps:
    - image: docker.io/alpine/openssl
      name: generate-secret
      resources: {}
      script: |
        #!/bin/sh

        echo "Generating New Password..."

        openssl rand -base64 $(params.SECRET_LENGTH) > pass-temp

    - image: 'docker.io/alpine/k8s:1.20.7'
      name: replace-secret
      resources: {}
      script: >
        #!/bin/sh

        echo "Generating Secret..."  

        NEW_PASSWORD=$(cat pass-temp)

        rm pass-temp 

        NEW_SECRET_NAME=$(params.SECRET_NAME)-$(date +%s)
        # echo NEW_SECRET_NAME > $(results.name)

        kubectl -n $(params.PROJECT_NAME) create secret generic
        $NEW_SECRET_NAME \
          --from-literal=database-name=$(params.DB_NAME) \
          --from-literal=database-user=$(params.USERNAME) \
          --from-literal=database-password=$NEW_PASSWORD \
          --dry-run=client -o yaml > secret.yaml

        echo "Generated $NEW_SECRET_NAME:"

        cat secret.yaml
    - image: 'docker.io/alpine/k8s:1.20.7'
      name: apply-secret
      resources: {}
      script: >
        #!/bin/sh

        kubectl apply -f secret.yaml