apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: new-secret
spec:
  params:
    - name: SECRET_LENGTH
    - name: PROJECT_NAME
    - name: SECRET_FILENAME     
    - name: SECRET_NAME 
    - name: DB_NAME
    - name: USERNAME
  results:
    - name: name
      description: New Secret Name
  steps:
    - image: docker.io/alpine/openssl
      name: generate-secret
      script: |
        #!/bin/sh

        echo "Generating New Password..."

        openssl rand -base64 $(params.SECRET_LENGTH) > pass-temp

    - image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      name: replace-secret
      script: >
        #!/bin/sh

        echo "Generating Secret..."  

        NEW_PASSWORD=$(cat pass-temp)

        rm pass-temp 

        NEW_SECRET_NAME=$(params.SECRET_NAME)-$(date +%s)
        $NEW_SECRET_NAME | tee $(results.name.path)

        oc -n $(params.PROJECT_NAME) create secret generic
        $NEW_SECRET_NAME \
          --from-literal=database-name=$(params.DB_NAME) \
          --from-literal=database-user=$(params.USERNAME) \
          --from-literal=database-password=$NEW_PASSWORD \
          --dry-run=client -o yaml > $(params.SECRET_FILENAME)

        echo "Generated $NEW_SECRET_NAME:"

        cat secret.yaml