apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: seal-secret
spec:
  steps:
    - image: 'docker.io/alpine/k8s:1.20.7'
      name: fetch-cert
      resources: {}
      script: >
        #!/bin/sh

        wget "https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/kubeseal-linux-amd64" -O kubeseal 
        
        install -m 755 kubeseal /usr/local/bin/kubeseal

        kubeseal