apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: seal-secret
spec:
  params:
   - name: SEALED_SECRETS_CONTROLLER_NS
     description: Namespace the sealed-secrets controller is deployed in
     default: sealed-secrets
   - name: INPUT_SECRET_FILENAME
     description: Secret filename for kubeseal to encrypt
   - name: OUTPUT_SEALED_SECRET_FILENAME
     description: Name of output sealed secret filename
  steps:
    - image: quay.io/samuele_chinellato_ibm/ubi8-kubeseal:0.0.1
      name: kubeseal-reencrypt-secret
      script: >
        #!/bin/sh

        echo "Encrypting secret $(params.INPUT_SECRET_FILENAME)"

        kubeseal --controller-namespace $(params.SEALED_SECRETS_CONTROLLER_NS) < $(params.INPUT_SECRET_FILENAME) > $(params.OUTPUT_SEALED_SECRET_FILENAME)

        echo "Created secret $(params.OUTPUT_SEALED_SECRET_FILENAME):"

        cat $(params.OUTPUT_SEALED_SECRET_FILENAME)