apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: seal-secret
spec:
  workspaces:
    - name: source
      description: contains the cloned git repo
  params:
   - name: SEALED_SECRETS_CONTROLLER_NS
     type: string
     description: Namespace the sealed-secrets controller is deployed in
     default: kube-system
   - name: INPUT_SECRET
     type: string
     description: Name and path to secret for kubeseal to encrypt
   - name: OUTPUT_SEALED_SECRET
     type: string
     description: Name of output sealed secret
   - name: TARGET_NAMESPACE
     type: string
     description: Namespace to create the secret in
  steps:
    - image: 'docker.io/samchinellato/ubi8-kubeseal:0.19.1'
      name: kubeseal-reencrypt-secret
      workingDir: $(workspaces.source.path)
      script: >
        #!/bin/sh

        echo "Encrypting secret $(params.INPUT_SECRET)"
        
        kubeseal --controller-namespace $(params.SEALED_SECRETS_CONTROLLER_NS) \
          -o yaml <$(params.INPUT_SECRET) \
          -n $(params.TARGET_NAMESPACE) > $(params.OUTPUT_SEALED_SECRET)

        echo "Created secret $(params.OUTPUT_SEALED_SECRET):"

        cat $(params.OUTPUT_SEALED_SECRET)