apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
spec:
  params:
    - name: DEPLOYMENT
      default: 'postgresql'
    - name: TYPE
      default: 'config'
    - name: NEW_SECRET_NAME
  steps:
    - image: 'docker.io/alpine/k8s:1.20.7'
      name: patch-yaml
      resources: {}
      script: >
        #!/bin/sh

        IMAGE=$(kubectl get deployment$(params.TYPE) $(params.DEPLOYMENT) -o=jsonpath='{$.spec.template.spec.containers[:1].image}')
        
        echo $IMAGE

        echo "spec:
          template:
            spec:
              containers:
              - env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: $(params.NEW_SECRET_NAME)
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: $(params.NEW_SECRET_NAME)
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: $(params.NEW_SECRET_NAME)
                image: $IMAGE
                name: postgresql
        " > patch-file.yaml

        cat patch-file.yaml
    
    - image: 'docker.io/alpine/k8s:1.20.7'
      name: update-deployment
      resources: {}
      script: >
        #!/bin/sh

        kubectl patch deploymentconfig postgresql --patch-file=patch-file.yaml
      