apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations: {}
  labels:
    name: sealed-secrets-service-proxier
  name: sealed-secrets-service-proxier
rules:
  - apiGroups:
      - ""
    resourceNames:
      - sealed-secrets
    resources:
      - services
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - 'http:sealed-secrets:'
      - 'http:sealed-secrets:http'
      - sealed-secrets
    resources:
      - services/proxy
    verbs:
      - create
      - get