apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/version: v0.16.0