apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sealed-secrets
  name: sealedsecret-admin
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealedsecret-admin
  namespace: sealed-secrets
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: sealed-secrets
roleRef:
  kind: Role
  name: sealedsecret-admin
  apiGroup: rbac.authorization.k8s.io